### ISSUE TITLE
:first-child does not behave like the demo

### ISSUE THREAD

**Issue by ProgVal** [mwhooker/jsonselect#5] opened 2015-03-22 18:52 UTC
On the [demo website](http://jsonselect.org/#tryit) you can do `.drinkPreference :first-child` to get the first child, whatever its type (`"whiskey"`).

However, this implementation does not behave this way: unless a type is given, it does not return anything.

```
$ python -m jsonselect ".drinkPreference :first-child" conformance_tests/upstream/level_1/basic.json
$ python -m jsonselect ".drinkPreference string:first-child" conformance_tests/upstream/level_1/basic.json
"beer"
```

**Comment by ProgVal** [comment] 2015-03-22 21:24
Update: I edited my initial message to make it clearer what the issue is

**Comment by mwhooker** [comment] 2015-03-23 04:41
Dupe of #1

**Closed by mwhooker** 2015-03-23 04:41 UTC
